### ISSUE TITLE
Vraag strapi

### ISSUE THREAD

**Issue by GithubMVS** [GithubMVS/MakeItPersonal#3]
Beste,

Ik had nog enkele vragen omtrend de taak die we hadden meegekregen van dev 4,

1: bij het deployen van mijn website ( [via vercel] om dit te testen) kreeg ik een foutmelding toen ik mijn code van mijn "develop-branch" naar mijn "main-branch" wilde pushenn ik kan dus niet pushen naar mijn main. Ik heb dit dan later opgelost door mijn "master" branch (die github voor mij heeft gemaakt) als "default" te zetten. Maar zou toch liever de "main" branch gebruiken. Hoe los ik dit best op?
- error: "fatal: refusing to merge unrelated histories"

2: bij het deployen van mijn website kreeg ik deze foutmelding (zie foto). Hier zegt het dus dat het normalize.css niet kan inlezen. Hoe los ik dit best op?
<img width="541" alt="Screenshot 2021-04-11 at 16 45 47" src="https://user-images.githubusercontent.com/72080712/114309001-014e5b00-9ae6-11eb-8614-19980c9233a7.png">

3: Is het een vereiste om met strapi of een andere headless cms te gebruiken? Of mag dit een puur next.js project zijn? (met bijhoorende dingen [API's, libraries, etc...])

Alvast bedankt voor uw reactie
Matisse

**Comment by SimonVanherweghe** [comment]
Best een issue per vraag aanmaken in het vervolg.

1. Ik veronderstel dat je jouw develop branch met de main branch wilde mergen? Github maakt geen master branches meer aan, deze heten nu standaard 'main'. Het kan wel zijn dat je bv nog lokaal een 'master' branch hebt staan, dan kan je die idd niet pushen naar de main. Goed checken hoe alles heet. In worst case jouw .git map wissen van je project, opnieuw initialiseren en pushen naar (eventueel een nieuwe) repo  (echt in worst case: je verliest hierbij heel jouw git history)

2. Heb je die normalize als [global stylesheet](https://nextjs.org/docs/basic-features/built-in-css-support) toegevoegd?

3. Het is geen vereiste om met strapi te werken, we willen je zelf aanmoedigen om [eens iets anders](https://jamstack.org/headless-cms/) te proberen. Zonder iets van backend lijkt me deze opdracht onmogelijk. Dus ja: maak gebruik van API's
