### ISSUE TITLE
vraag API call

### ISSUE THREAD

**Issue by GithubMVS** [GithubMVS/MakeItPersonal#4]
Beste, voor mijn project zou ik de current url moeten ophalen om een API te kunnen gebruiken (spotify API). Ik gebruik hiervoor de Authorization code methode. 
- link uitleg spotiy API: https://developer.spotify.com/documentation/general/guides/authorization-guide/ 

Ook is het interessant om te melden dat ik de library spotify-web-api-node gebruik voor Authentication gebruik.
Link: https://github.com/thelinmichael/spotify-web-api-node
- Ik gebruik deze authenticatie om die een code te maken en deze om te zetten naar  acces token en een refresh token, waarmee ik dus de user aan kan "herkennen". Dit moet ook op een "server" gebeuren omdat het mijn clientSecret (van SpotifyAPI) nodig heeft
   - voor deze server gebruik ik express en spotify-web-API
       - server code:
 https://github.com/GithubMVS/MakeItPersonal/blob/f5b57f37f554462c20211028ed970f198a81bf06/server/server.js#L1-L26
- foto van mijn package.json die ik hiervoor gebruik
https://github.com/GithubMVS/MakeItPersonal/blob/f5b57f37f554462c20211028ed970f198a81bf06/server/package.json#L1-L11
- foto van hoe mijn mapje server eruit ziet
![image](https://user-images.githubusercontent.com/72080712/114370383-b5e88b00-9b7f-11eb-8b55-ab08ba2cf378.png)
  

Dit had ik gedaan met deze code:
- const code = new URLSearchParams(window.location.search).get('code')
   - deze code pakt de voor mij al gelukte gegenereerde code in mijn url en zet deze in een variable 

Nu blijkt dat ik deze niet kan gebruiken in next.js en had ik online deze uitleg gevonden + deze "oplossing"
- NextJS is a framework that allows you to build Static and Server Side Rendered Apps. It uses NodeJS to render your application and window is not defined in NodeJS. That means that we need to be careful that our code that accesses the window object is not run in NodeJS.

artikel: https://morioh.com/p/f7b08fe33a67

1: Use the useEffect hook
- kan ik niet gebruiken aangezien ik deze url nog meerdere maal nodig heb in andere componenten en dat ik deze variable niet kan aansprekene buiten de useEffect hook
- zelf krijg ik bij iedere refresh wel de url in een variable (en kan ik deze ook console.loggen in de useEffect hook) maar buiten deze useEffect hook kan ik deze niet gebruiken.

Mijn vraag is dus: Hoe pak ik de current url in next.js (en zet ik deze in een variable [zoals mijn gegeven code])

Hoe los ik dit best op?

Alvast bedankt 
Matisse

**Comment by SimonVanherweghe** [comment]
> Dit moet ook op een "server" gebeuren omdat het mijn clientSecret (van SpotifyAPI) nodig heeft

Hiervoor kan je net de API routes van Next gebruiken!

Heb je hier al eens op gegoogled? Je moet het warm water niet opnieuw uitvinden...
https://leerob.io/blog/spotify-api-nextjs
https://github.com/chrisjobando/spotify-nextjs
