### ISSUE TITLE
vraag mappen structuur

### ISSUE THREAD

**Issue by GithubMVS** [GithubMVS/MakeItPersonal#5]
Beste,

Alvast eerst een bedankje voor uw/jullie vorige feedback, deze heeft me enorm vooruit geholpen!

Ik had nog een concrete vraag over hoe ik best mijn paginastructuur in elkaar steek.

Momenteel heb ik ze opgelijst op deze manier (in de page folder):
![image](https://user-images.githubusercontent.com/72080712/114402505-302b0680-9ba4-11eb-846e-c1e8e7c5c3a0.png)
- alles dat u op de foto ziet is een subpagina'tje (op app.js na) waar ik (kort door de bocht weliswaar)  stap per stap doorga met Link in next.js en de user een vraag stel en die data in een object array opslaag. --> en deze zouden later nog moet doorgestuurd worden naar de "playlistAndMessage" om daar die data te gebruiken om die specifieke data te gebruiken in mijn API
  - nu geeft dit wel enkele problemen met zich mee:
     - ik kan niets via props meegeven omdat dit aparte pagina's zijn.
     - ik kan hierbij wel useContext gebruiken maar dan zou ik dit voor de 8+ pagina's moeten maken en ik weet niet of dit wel zo efficiënt is.
    
Nu had ik dus de vraag of het "oké" was om 1 pagina te maken (in de page folder) genaamd "inputs" en daar alle "subpagina'tjes" als components mee te geven waar ik door kan gaan met bijvoorbeeld een if-else statement. Zou dit oké zijn of heeft dit enkele slechte neveneffecten? zoals bijvoorbeeld: "slechte rendering/SEO, etc..."

2: Ik heb nu momenteel 2 pagina's, index en inputs page, beide hebben niets met elkaar te maken enkel dat je een variable hebt die ze zouden moeten delen. Nu is het probleem dat ik inputs niet als component gebruik in miin index page maar zou de waarde van de variable wel moeten kunnen delen. useRouter heb ik hiervoor al gebruikt maar dat werkte niet hierbij. Hebben jullie toevallig een idee hoe ik data doorgeef door 2 verschillende pages.

<img width="1628" alt="Screenshot 2021-04-13 at 10 44 36" src="https://user-images.githubusercontent.com/72080712/114524366-708e9100-9c45-11eb-96a6-a8921cdf3fcd.png">

Alvast bedankt voor uw reactie
Matisse

**Comment by benoitboucart** [comment]
Je kan dit perfect combineren in één pagina waar je dan conditioneel stappen toont (met links naar volgende / vorige stap enz). Je kan deze "wizard" zelf from scratch programmeren of een extern component voor gebruiken (Google bvb.: react wizard / multistep form om inspiratie op te doen) 

Dit kan eventueel ook in combinatie met dynamic routes (de stap nummer / naam is dan de "dynamische" parameter. 

2e vraag: routes inlezen doe je inderdaad niet met `window object`. Gebruik hiervoor de `useRouter` hook van Next. Meer info: https://nextjs.org/docs/routing/dynamic-routes

Succes.
