### ISSUE TITLE
vraag layout verschillende browsers

### ISSUE THREAD

**Issue by GithubMVS** [GithubMVS/MakeItPersonal#6]
Beste,

Ik had gemerkt dat mijn design er compleet "anders" uit ziet als ik mijn design/site open in andere browsers. Zo is bijvoorbeeld mijn tekst veel kleine op de firefox/ browser. Weet u/jullie toevallig hoe dit komt en hoe ik dit kan oplossen?

Zelf heb ik de reset.css en dergelijke toegevoegd.
het rode is een foto

Hieronder een voorbeeld:
firefox browser
<img width="839" alt="Screenshot 2021-04-14 at 20 51 43" src="https://user-images.githubusercontent.com/72080712/114764197-ef79eb80-9d63-11eb-88d0-bd4046c28ffc.png">

google chrome browser
<img width="900" alt="Screenshot 2021-04-14 at 20 52 30" src="https://user-images.githubusercontent.com/72080712/114764205-f0ab1880-9d63-11eb-839a-06d7a3054749.png">

**Comment by SimonVanherweghe** [comment]
Vreemd, iets van extensies draaien in chrome/ff? Heb je dit ook in guest mode?

Heb je het al ergens online staan zodat we het daar kunnen bekijken?

Ik zie ook dat je een reset én een normalize gebruikt, dat is niet logisch, kies één van de 2
Let ook op met hoofdletters, files staan met een hoofdletter geschreven, maar je roept ze op zonder...
