### ISSUE TITLE
Vraag ophalen data

### ISSUE THREAD

**Issue by GithubMVS** [GithubMVS/MakeItPersonal#7]
Beste,

Ik wilde voor mijn api calls "getStaticProps" gebruiken om eerst mijn data op te halen voor dat ik deze gebruik in mijn functional components. 

Nu zit ik wel met dit probleem: 

- De data die ik ophaal van de API is afhankelijk van de inputs die ik geef (of de user wel of niet op een button klikt, op welke button etc...). Ik store dan die data in een useState(s) en/of array('s) om daar dan nog eens een berekening op te maken (om dan later de waarde van de berekening te gebruiken om specifieke data van de API te pakken.[nog niet gedaan]) en die API calls te storen op mijn webpage. Ik kan useStatic props dan toch niet gebruiken omdat ik al data zou ophalen voor dat de user de inputs heeft kunnen gebruiken dus het zou niet weten wat het precies moet oppakken...
- Een voorbeeld hiervan is bijvoorbeeld dat ik door de input van de user 3 bepaalde muziekGenre's (van de +- 12 muziekgenre's)zou ophalen in een api-call om dan later nog eens een api-call te doen om dan nogmaals 5 nummers per genre op te halen. Normaal gezien haal je alle data op om deze dan in te laden op de webpagina, maar nu is dus de data anders naarmaten op welke knop de user drukt.
  - Dit moet gebeuren via 2 api calls genaamd (spotifyApi.getCategory en getAlbumTracks) link: https://github.com/BrOrlandi/spotify-web-api-node 

Ben ik hier verkeerd in en kan ik het toch gebruiken? Of gebruik ik best iets anders?

Alvast bedankt voor uw response
Matisse

**Comment by SimonVanherweghe** [comment]
getStaticProps runt a at build time, op de server, dus voor de client het krijgt, voor dat de bezoeker het te zien krijgt. Dus neen: je kan dit niet gebruiken met user input. *

Je zou wel alle categorieën kunnen ophalen, zolang dit een beetje binnen de perken blijft (als het er geen honderden zijn) en deze dan client-side filteren. Ik ga er vanuit dat die categorieën niet veel wijzigen, anders heeft het ook niet veel nut natuurlijk.

Als je client-side dingen wil (moet) ophalen, dan kan je de Spotify API aanroepen vanuit eigen aangemaakte API routes in Next.js (zie video over de buttondown integratie). Je kan dit gewoon via fetch doen, maar bekijk ook eens swr of react-query.
Indien je geen gebruik moet maken van secrets of zo, dan kan je ook gewoon die Spotify API aanroepen rechtstreeks van op de client.

(*) Je kan wel parameters meegeven via een route en zo in theorie alles binnen trekken, maar dan zou je héél Spotify static moeten renderen... Totaal niet praktisch dus.
