### ISSUE TITLE
Vraag linken met strapi

### ISSUE THREAD

**Issue by GithubMVS** [GithubMVS/MakeItPersonal#8]
Beste,

Voor mijn project zou ik strapi willen linken met mijn al bestaand next.js project. 

Voor wat wil ik strapi gebruiken?
- ik haal data via de spotify api op via client side. Nu wil ik die resultaten die ik dus via client side ophaal in een strapi database zetten om later elk resultaat (resulaten === id's ) uit te laden via een API met Dynamic Routes van next.js om dus voor elk resultaat een link te maken naar de info dat dit resultaat bevat (liedjes van spotify api, personal message, etc...). voor de spotify API zelf gebruik ik een gemaakte server + authenticatie die u hieronder kan terugvinden.

gemaakte server

https://github.com/GithubMVS/MakeItPersonal/blob/8aaa81c5e720acfef721065958ba0cf6cd55a472/server/server.js#L1-L54

authenticatie

https://github.com/GithubMVS/MakeItPersonal/blob/8aaa81c5e720acfef721065958ba0cf6cd55a472/constant/useAuth.js#L1-L47

Hoe link ik het beste strapi met een bestaand next.js project om dit goed te realiseren? 

Alvast bedankt voor uw response
Matisse

**Comment by SimonVanherweghe** [comment]
Wat bedoel je precies met linken? Data versturen naar Strapi?
Dat is gewoon een post doen naar de juiste REST API url.

**Comment by GithubMVS** [comment]
Beste, 

Het probleem is hierbij al opgelost, bedankt voor uw terugkoppeling.
Al had ik nog wel een extra vraag in verband met strapi:
- ik zou graag 2 arrays maken in de 'content-types-builder' van strapi om bepaalde data later in te 'storen' Hoe doe ik dit best?

fotovoorbeeld
- de "spotifyGenres" en "spotifySongs" zouden arrays moeten zijn waar ik door loop met .map om voor elke waarde nog een API call te doen via de client-side voor mijn spotify-api
![Screenshot 2021-04-22 at 01 29 25](https://user-images.githubusercontent.com/72080712/115634915-d85e6f00-a30a-11eb-98a2-fbd357819079.png)
![Screenshot 2021-04-22 at 01 29 38](https://user-images.githubusercontent.com/72080712/115634916-d98f9c00-a30a-11eb-9c07-3b39ccdca9ba.png)


Hoe doe ik dit best en/of is er een betere manier

Alvast bedankt voor uw terugkoppeling
Matisse

**Comment by GithubMVS** [comment]
Beste,

Het probleem is hierbij al opgelost, bedankt voor uw terugkoppeling.
Al had ik nog wel een extra vraag in verband met strapi:
- ik zou graag 2 arrays maken in de 'content-types-builder' van strapi om bepaalde data later in te 'storen' Hoe doe ik dit best?

fotovoorbeeld:

![Screenshot 2021-04-22 at 01 29 25](https://user-images.githubusercontent.com/72080712/115635145-54f14d80-a30b-11eb-94c9-eb1c3ebf006b.png)

![Screenshot 2021-04-22 at 01 29 38](https://user-images.githubusercontent.com/72080712/115635146-5589e400-a30b-11eb-8d24-16b7e59721f3.png)

- de "spotifyGenres" en "spotifySongs" zouden arrays moeten zijn waar ik door loop met .map om voor elke waarde nog een API call te doen via de client-side voor mijn spotify-api

Hoe doe ik dit best en/of is er een betere manier

Alvast bedankt voor uw terugkoppeling
Matisse

**Comment by SimonVanherweghe** [comment]
Voor die genres en songs kan je components gebruiken. Hebben we ook al eens in het labo gebruikt.

Data posten van Next naar Strapi is, wederom, via fetch een post doen naar uw Strapi API
