### ISSUE TITLE
Vraag euthenticatie next JS project

### ISSUE THREAD

**Issue by GithubMVS** [GithubMVS/MakeItPersonal#9]
Beste, 

Voor mijn project maak ik gebruik van de spotifyAPI. Hierbij Heb je een "accestoken" voor nodig, waar je dus eerst voor moet inloggen op spotify en na het inloggen is er hier een Redirect URI om je naar die specifieke pagina te sturen na je bent ingelogt met spotify. Deze specifieke pagina bevat dan een token in de url die je moet fetchen en gebruiken om je spotify request te doen. Nu zit ik met het probleem dat ik de redirect URI niet kan zetten aangezien ik via dynamic routes werk en deze dus constant anders is. (ene keer results/23 andere keer results/24 etc...) 

Hieronder een foto met meer uitleg
<img width="541" alt="Screenshot 2021-04-23 at 10 12 17" src="https://user-images.githubusercontent.com/72080712/115840850-6aa26800-a41c-11eb-945c-8cc6183d409a.png">

Hoe pak ik dit best aan?

Alvast bedankt voor uw response
Matisse

**Comment by SimonVanherweghe** [comment]
Je moet die redirect pagina als tussenstap implementeren.
Voorzie een vaste pagina voor de callback. Deze leest de token uit en bewaart hem ergens (in de state of localstorage of zo) Je kan op die pagina een link voorzien waarmee de gebruiker nog zelf verder moet navigeren ofwel doe je dat automatisch mbv next/router

**Comment by GithubMVS** [comment]
Beste,

Alvast bedankt voor uw snelle response.

Hier had ik aan gedacht maar zal dit dan geen probleem zijn eens je de specifieke url doorstuurt naar een andere persoon? Want je wilt "songs" zien op deze pagina zelf nog.  Zelf had ik ook al gedacht om de liedjes op die pagina statisch te maken (kunnen niet afspelen want worden uitgelezen uit de database + geen spotify API) en dan als je op een knop duwt dat je op een andere 'statische' pagina komt (waar ik de accesToken wel kan vragen) waarbij al die specifieke liedjes worden uitgeladen en waar je ze kunt afspelen (in browser of op spotify). Maar hierbij moet ik dus wel het id kunnen meegeven na het klikken van de knop (dit kan met state maar het id doorgeven naar de andere pagina is het grote probleem hierbij) zodat ik  a:  weet welke nummers ik moet toevoeggen aan spotify + b: welke nummers ik moet halen uit de database (alle nummers van id 20 bijvoorbeeld) om deze in uit te laden op het beeldscherm en/of in een spotiify playlist

Alvast bedankt voor uw response
Matisse

**Comment by SimonVanherweghe** [comment]
Ik kan niet helemaal volgen, maar het zou zo iets moeten zijn;

De zender:
- Logt in met spotify, kan via-via liedjes selectere, afspelen etc...
- Stuurt een link door naar de ontvanger

De ontvanger:
- Moet je verplichten om in te loggen op spotify vooraleer alles te kunnen zien/doen

ofwel:

- Een basic weergave aanbieden, waarvoor hij niet moet ingelogd zijn. Als hij de full-experience wil, dan moet hij ook terug inloggen met zijn account. Dan heb je een andere token waar je ook weer mee de nodige zaken op ophalen.

**Comment by GithubMVS** [comment]
Beste, 

Alvast bedankt voor uw response.

Kan u vandaag of morgen 10 minuten vrij maken zodat ik het wat duidelijker kan uitleggen en we er eventueel samen uit kunnen komen.

Alvast bedankt voor uw response
Matisse

**Comment by SimonVanherweghe** [comment]
Boek gerust een consult in op maandag of woensdag
